# Generated by Django 6.0.2 on 2026-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProyectoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nombre_organizacion', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('descripcion_proyecto', models.TextField()),
                ('presupuesto', models.CharField(max_length=40)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('acepta_aviso', models.BooleanField()),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de proyecto',
                'verbose_name_plural': 'Solicitudes de proyectos',
                'db_table': 'solicitudes_proyectos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
